/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hieucao.sieuthiBigK.sellerController;

import com.fasterxml.jackson.databind.module.SimpleAbstractTypeResolver;
import hieucao.sieuthiBigK.menuController.Invoice;
import hieucao.sieuthiBigK.sellerController.BarcodeScanner;
import hieucao.sieuthiBigK.loginView.Login;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Selling extends javax.swing.JFrame{
    
    
    
       /**
     * Creates new form Selling
     */
    public  static String rcbc="";
    public  static String cus_id="";
    private static int clickedCounter=0;
    private DefaultTableModel tableModel;
    private BarcodeScanner barcodeScanner;
    
    
    
    public Selling() {
        initComponents();
        SelectSeller();
        GetCat();
        GetCus();
        
        
    }
    Connection Con = null;
    Statement St =null;
    ResultSet Rs =null;
    
    
    
    public void SelectSeller()
    {
        try {
            //load last billID
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket","root","");
            St = Con.createStatement();
            Rs = St.executeQuery("SELECT * FROM extra WHERE exid = 1");
            if(Rs.next()){
               BillId.setText(Rs.getString("val")); 
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        //plus new bill
        int i = Integer.valueOf(BillId.getText());
        i++;
        BillId.setText(String.valueOf(i));
    }
    
    public void GetCat(){
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket","root","");
            St = Con.createStatement();
            String Query ="Select * from product";
            Rs = St.executeQuery(Query);
            while (Rs.next()) {                
                String MyCat =Rs.getString("PRODNAME");
                CatCb.addItem(MyCat);
                
            }     
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void GetCus(){
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket","root","");
            St = Con.createStatement();
            String Query ="Select * from customer";
            Rs = St.executeQuery(Query);
            while (Rs.next()) {                
                String MyCus =Rs.getString("CUSNAME");
                CusCb.addItem(MyCus);
            }
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    

    
    int NewQty;
    Double ProdTot =0.0,GrdTotal=0.0;
    public void update(){
        try {
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket","root","");
                String Query = "Update PRODUCT set PRODQTY="+NewQty+" where PRODNAME='" + CatCb.getSelectedItem().toString()+"'";
                Statement Add = Con.createStatement();
                Add.executeUpdate(Query);
            } catch (SQLException e) {
                e.printStackTrace();
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BillId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ProdQty = new javax.swing.JTextField();
        AddBtn = new javax.swing.JButton();
        ClearBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        POSTbl = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        Invoice = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Paid = new javax.swing.JTextField();
        Balance = new javax.swing.JTextField();
        CatCb = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        CusCb = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        RecentQty = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        CartPrice = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        BCode = new javax.swing.JTextField();
        RmvAll = new javax.swing.JButton();
        SaveBill = new javax.swing.JButton();
        PrintBill1 = new javax.swing.JButton();
        Unit = new javax.swing.JTextField();
        seller = new javax.swing.JTextField();
        dateChoose = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(550, 0, 525, 410));
        setUndecorated(true);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(1137, 937));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Raleway ExtraBold", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("POS BILLING");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Raleway ExtraBold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("BILLID");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Raleway ExtraBold", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 102));
        jLabel4.setText("PRODUCT");

        BillId.setEditable(false);
        BillId.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        BillId.setBorder(null);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Raleway ExtraBold", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 102));
        jLabel5.setText("ADD QTY");

        ProdQty.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        ProdQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdQtyActionPerformed(evt);
            }
        });

        AddBtn.setBackground(new java.awt.Color(255, 102, 102));
        AddBtn.setFont(new java.awt.Font("Raleway Light", 1, 18)); // NOI18N
        AddBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddBtn.setText("Add to Cart");
        AddBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102), 3));
        AddBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddBtnMouseClicked(evt);
            }
        });
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        ClearBtn.setBackground(new java.awt.Color(255, 102, 102));
        ClearBtn.setFont(new java.awt.Font("Raleway Light", 1, 18)); // NOI18N
        ClearBtn.setForeground(new java.awt.Color(255, 255, 255));
        ClearBtn.setText("Remove");
        ClearBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102), 3));
        ClearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearBtnMouseClicked(evt);
            }
        });
        ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBtnActionPerformed(evt);
            }
        });

        POSTbl.setFont(new java.awt.Font("Raleway Medium", 0, 14)); // NOI18N
        POSTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "QUANTITY", "PRICE", "BARCODE"
            }
        ));
        POSTbl.setGridColor(new java.awt.Color(102, 102, 102));
        POSTbl.setRowHeight(25);
        POSTbl.setSelectionBackground(new java.awt.Color(255, 102, 102));
        POSTbl.setSelectionForeground(new java.awt.Color(255, 255, 255));
        POSTbl.setShowGrid(true);
        jScrollPane1.setViewportView(POSTbl);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Raleway ExtraBold", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 102));
        jLabel9.setText("CART");

        Invoice.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setText("TOTAL:");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setText("BALANCE");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 102));
        jLabel8.setText("PAID:");

        Paid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Paid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PaidKeyReleased(evt);
            }
        });

        Balance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        CatCb.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        CatCb.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                CatCbPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        CatCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatCbActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Raleway ExtraBold", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 102));
        jLabel11.setText("CUSTOMER");

        CusCb.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        CusCb.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                CusCbPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        CusCb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CusCbMouseClicked(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Raleway ExtraBold", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 102));
        jLabel12.setText("QUANTITY");

        RecentQty.setEditable(false);
        RecentQty.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        RecentQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecentQtyActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Raleway ExtraBold", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 102));
        jLabel13.setText("PRICE");

        CartPrice.setEditable(false);
        CartPrice.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        CartPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartPriceActionPerformed(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Raleway ExtraBold", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 102, 102));
        jLabel14.setText("BARCODE");

        BCode.setEditable(false);
        BCode.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        BCode.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                BCodePropertyChange(evt);
            }
        });

        RmvAll.setBackground(new java.awt.Color(255, 102, 102));
        RmvAll.setFont(new java.awt.Font("Raleway Light", 1, 18)); // NOI18N
        RmvAll.setForeground(new java.awt.Color(255, 255, 255));
        RmvAll.setText("Remove All");
        RmvAll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102), 3));
        RmvAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RmvAllMouseClicked(evt);
            }
        });
        RmvAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RmvAllActionPerformed(evt);
            }
        });

        SaveBill.setBackground(new java.awt.Color(255, 102, 102));
        SaveBill.setFont(new java.awt.Font("Raleway Light", 1, 18)); // NOI18N
        SaveBill.setForeground(new java.awt.Color(255, 255, 255));
        SaveBill.setText("Save Bill");
        SaveBill.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102), 3));
        SaveBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveBillMouseClicked(evt);
            }
        });
        SaveBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBillActionPerformed(evt);
            }
        });

        PrintBill1.setBackground(new java.awt.Color(255, 102, 102));
        PrintBill1.setFont(new java.awt.Font("Raleway Light", 1, 18)); // NOI18N
        PrintBill1.setForeground(new java.awt.Color(255, 255, 255));
        PrintBill1.setText("Print Bill");
        PrintBill1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102), 3));
        PrintBill1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrintBill1MouseClicked(evt);
            }
        });
        PrintBill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBill1ActionPerformed(evt);
            }
        });

        Unit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        seller.setEditable(false);
        seller.setFont(new java.awt.Font("Segoe UI Historic", 2, 18)); // NOI18N
        seller.setToolTipText("");
        seller.setBorder(null);

        dateChoose.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(46, 46, 46)
                                        .addComponent(ProdQty))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel12))
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CatCb, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(BillId)
                                                .addComponent(CusCb, 0, 182, Short.MAX_VALUE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14))
                                        .addGap(38, 38, 38)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BCode)
                                            .addComponent(CartPrice)
                                            .addComponent(RecentQty))))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(dateChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(191, 191, 191)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SaveBill, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(Unit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Invoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(Paid)
                                            .addComponent(Balance, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(62, 62, 62)
                                        .addComponent(PrintBill1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(109, 109, 109))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(477, 477, 477))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(229, 229, 229)
                                                .addComponent(jLabel9)))
                                        .addGap(80, 80, 80))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(seller, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RmvAll, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BillId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CusCb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(CatCb, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(RecentQty, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Invoice, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Paid, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Balance)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(CartPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(BCode, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ProdQty, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Unit, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                .addGap(82, 82, 82)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RmvAll, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaveBill, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrintBill1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(seller, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(dateChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Raleway ExtraBold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(255, 102, 102));
        jLabel10.setFont(new java.awt.Font("Raleway ExtraBold", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Logout");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 1211, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1055, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProdQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProdQtyActionPerformed
    int i =0;
    String ID,Name, Quantity, Price,Barcode;
    private void AddBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddBtnMouseClicked
        if(ProdQty.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Missing Infor");
        }else if(Integer.valueOf(RecentQty.getText()) <Integer.valueOf(ProdQty.getText())){
            JOptionPane.showMessageDialog(this, "Not Enough In Stock");
        }else{
            i++;
            ProdTot=Double.valueOf(CartPrice.getText()) * Integer.valueOf(ProdQty.getText());
            GrdTotal= GrdTotal+ProdTot;
            NewQty =Integer.valueOf(RecentQty.getText())- Integer.valueOf(ProdQty.getText());
            RecentQty.setText(String.valueOf(NewQty));
            Invoice.setText(Math.round(GrdTotal * 100.0) / 100.0+" $");
            tableModel =(DefaultTableModel)POSTbl.getModel();
            ID=String.valueOf(i);
            Name=CatCb.getSelectedItem().toString();
            Quantity=ProdQty.getText();
            Price=CartPrice.getText();
            Barcode=BCode.getText();
            String[] add ={ID,Name,Quantity,Price,Barcode};
            tableModel.addRow(add);
            update();
            
        }
    }//GEN-LAST:event_AddBtnMouseClicked

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddBtnActionPerformed

    private void ClearBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearBtnMouseClicked
        try {
            if(i>0){
            tableModel =(DefaultTableModel)POSTbl.getModel();
            int rw =POSTbl.getSelectedRow();
            tableModel.removeRow(rw);
            i--;
            ProdTot=Double.valueOf(CartPrice.getText()) * Integer.valueOf(ProdQty.getText());
            GrdTotal= GrdTotal-ProdTot;
            NewQty =Integer.valueOf(RecentQty.getText())+ Integer.valueOf(ProdQty.getText());
            RecentQty.setText(String.valueOf(NewQty));
            Invoice.setText(Math.round(GrdTotal * 100.0) / 100.0+" $");
            update();
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_ClearBtnMouseClicked


    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked

        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void RecentQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecentQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecentQtyActionPerformed

    private void ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearBtnActionPerformed

    private void CatCbPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_CatCbPopupMenuWillBecomeInvisible
        String item =(String)CatCb.getSelectedItem();
        String Query ="Select * from product where PRODNAME= ?";
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket","root","");
            PreparedStatement St  = Con.prepareStatement(Query);
            St.setString(1,item);
            Rs = St.executeQuery();
            while (Rs.next()) {                
                String rcqty=Rs.getString("PRODQTY");
                String rcprc=Rs.getString("PRODPRICE");
                String rcun =Rs.getString("UNIT");
                rcbc=Rs.getString("BARCODE");
                RecentQty.setText(rcqty);
                CartPrice.setText(rcprc);
                BCode.setText(rcbc);
                Unit.setText(rcun);
            }     
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_CatCbPopupMenuWillBecomeInvisible

    private void CartPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CartPriceActionPerformed
    int k;
    private void RmvAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RmvAllMouseClicked
        tableModel =(DefaultTableModel)POSTbl.getModel();
              int rows = tableModel.getRowCount();
              Invoice.setText(0+" $");
              GrdTotal=0.0;
              paid=0.0;
              balance=0.0;
              Paid.setText("");
              Balance.setText("");
        while(rows>0) {
            try {
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket","root","");
                String Query2 ="Select * from product where PRODNAME='"+ tableModel.getValueAt(rows-1, 1).toString()+"'";
                St = Con.createStatement();
                Rs = St.executeQuery(Query2);
                while (Rs.next()) {   
                String rcqty=Rs.getString("PRODQTY");
                System.out.println(rcqty);
                k =Integer.valueOf(rcqty);
                }
                NewQty=k+Integer.valueOf(tableModel.getValueAt(rows-1, 2).toString());
                System.out.println(NewQty);
                System.out.println("");
                //Statement Add = Con.createStatement();
                //Add.executeUpdate(Query);
            } catch (SQLException e) {
                e.printStackTrace();
            }
            try {
                Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket","root","");
                String Query = "Update PRODUCT set PRODQTY="+NewQty+" where PRODNAME='" + tableModel.getValueAt(rows-1, 1).toString()+"'";
                Statement Add = Con.createStatement();
                Add.executeUpdate(Query);
            } catch (SQLException e) {
                e.printStackTrace();
            }
            rows--;
            tableModel.removeRow(rows);
            i--;
        }
    }//GEN-LAST:event_RmvAllMouseClicked

    private void RmvAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RmvAllActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RmvAllActionPerformed
    Double paid,invoice,balance;
    private void PaidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PaidKeyReleased
        paid =Double.valueOf(Paid.getText());
        invoice =Math.round(GrdTotal * 100.0) / 100.0;
        balance = invoice-paid;
        Balance.setText(String.valueOf(balance)+"$");
    }//GEN-LAST:event_PaidKeyReleased

    private void SaveBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveBillMouseClicked
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String theDate = dateFormat.format(dateChoose.getDate());
        if(clickedCounter ==0 ){
            JOptionPane.showMessageDialog(this, "Customer's name is unchecked");
        }else if(Paid.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Unpaid yet !!!");        
                    
        }else{
//bill DB    
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket","root","");
            PreparedStatement add =Con.prepareStatement("insert into BILL values(?,?,?,?,?,?)");
            add.setInt(1, Integer.valueOf(BillId.getText()));
            add.setInt(2, Integer.valueOf(cus_id));
            add.setString(3, CusCb.getSelectedItem().toString());
            add.setString(4, String.valueOf(invoice));
            add.setString(5, String.valueOf(balance));
            add.setDate(6, Date.valueOf(theDate));
            add.executeUpdate();
            //JOptionPane.showMessageDialog(this, "Data saved Successfully");
            
          
       
        } catch (Exception e) {
            e.printStackTrace();
        }
        //cart db
        tableModel =(DefaultTableModel)POSTbl.getModel();
        int rc =tableModel.getRowCount();
        for(int m=0; m<rc;m++){
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket","root","");
            PreparedStatement add =Con.prepareStatement("insert into CART (BillId, ProdName, Barcode, CartQty, CartPrice, TPrice) values(?,?,?,?,?,?)");
            add.setInt(1, Integer.valueOf(BillId.getText()));
            add.setString(2, tableModel.getValueAt(m, 1).toString() );
            add.setString(3, tableModel.getValueAt(m, 4).toString());
            add.setString(4, tableModel.getValueAt(m, 2).toString());
            add.setString(5, tableModel.getValueAt(m, 3).toString());
            add.setString(6, String.valueOf(Integer.valueOf(tableModel.getValueAt(m, 2).toString()) *Double.valueOf(tableModel.getValueAt(m, 3).toString())));
            add.executeUpdate();
            
            
          
       
        } catch (Exception e) {
            e.printStackTrace();
        }
        }
        
        
        try {
            String id =BillId.getText();
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket","root","");
            Statement Add = Con.createStatement();
            Add.executeUpdate("UPDATE extra SET val='"+id+"' WHERE exid = 1");
        } catch (Exception e) {
            System.out.println(e);
        }
            
         JOptionPane.showMessageDialog(this, "Data saved Successfully");
         SelectSeller();
         GetCat();
         GetCus();
         RecentQty.setText("");
         CartPrice.setText("");
         BCode.setText("");
         ProdQty.setText("");
         tableModel.setRowCount(0);
         i=0;
         ProdTot =0.0;
         GrdTotal=0.0;
         Invoice.setText("");
         Paid.setText("");
         Balance.setText("");
        }
        
    }//GEN-LAST:event_SaveBillMouseClicked

    private void SaveBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveBillActionPerformed

    private void CusCbPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_CusCbPopupMenuWillBecomeInvisible
        String item =(String)CusCb.getSelectedItem();
        String Query ="Select * from customer where CUSNAME= ?";
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket","root","");
            PreparedStatement St  = Con.prepareStatement(Query);
            St.setString(1,item);
            Rs = St.executeQuery();
            while (Rs.next()) {                
                cus_id=Rs.getString("CUSID");
            }     
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_CusCbPopupMenuWillBecomeInvisible

    private void PrintBill1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrintBill1MouseClicked
        // TODO add your handling code here:
        new Invoice().setVisible(true);
    }//GEN-LAST:event_PrintBill1MouseClicked

    private void PrintBill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBill1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrintBill1ActionPerformed

    private void CatCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatCbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CatCbActionPerformed

    private void BCodePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_BCodePropertyChange
        String item =BCode.getText();
        String Query ="Select * from product where BARCODE= ?";
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/supermarket","root","");
            PreparedStatement St  = Con.prepareStatement(Query);
            St.setString(1,item);
            Rs = St.executeQuery();
            while (Rs.next()) {                
                String rcqty=Rs.getString("PRODQTY");
                String rcprc=Rs.getString("PRODPRICE");
                RecentQty.setText(rcqty);
                CartPrice.setText(rcprc);
                String rcCatCb = Rs.getString("PRODNAME");
                CatCb.setSelectedItem(rcCatCb);
            }     
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_BCodePropertyChange

    private void CusCbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CusCbMouseClicked
        // TODO add your handling code here:
        clickedCounter++;
    }//GEN-LAST:event_CusCbMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Selling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Selling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Selling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Selling.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Selling().setVisible(true);
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    public javax.swing.JTextField BCode;
    private javax.swing.JTextField Balance;
    private javax.swing.JTextField BillId;
    public javax.swing.JTextField CartPrice;
    public javax.swing.JComboBox<String> CatCb;
    private javax.swing.JButton ClearBtn;
    private javax.swing.JComboBox<String> CusCb;
    private javax.swing.JLabel Invoice;
    private javax.swing.JTable POSTbl;
    private javax.swing.JTextField Paid;
    private javax.swing.JButton PrintBill1;
    public javax.swing.JTextField ProdQty;
    public javax.swing.JTextField RecentQty;
    private javax.swing.JButton RmvAll;
    private javax.swing.JButton SaveBill;
    public javax.swing.JTextField Unit;
    private com.toedter.calendar.JDateChooser dateChoose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField seller;
    // End of variables declaration//GEN-END:variables
}
